### ISSUE TITLE
Software problem in Windows

### ISSUE THREAD

**Issue by Dadmehr0** [Matinpirvali/tmr_p#1]
![Screenshot (1)](https://user-images.githubusercontent.com/109520109/231815159-8f44ed7a-a0d0-46e0-8caa-5c7300cd6dbf.png)
Before we want to place two versions in one software
I wrote both of them separately and tested them. I didn't encounter any problems in Windows. If there is a problem, report it

**Comment by Matinpirvali** [comment]
برنامه ارور Tk  میده

**Comment by Dadmehr0** [comment]
> برنامه ارور Tk  میده

هنوز هم با ایجاد تغییر ها ؟
ببنید من تو یک سیستم عامل ویندوز تست کردم حتا اسکرین شات هم گرفتم

**Comment by Matinpirvali** [comment]
الان اون ارور رفع شد ولی برنامه تموم می شده و به من چیز خاصی نمایش نمی دهد

**Comment by Dadmehr0** [comment]
> الان اون ارور رفع شد ولی برنامه تموم می شده و به من چیز خاصی نمایش نمی دهد

چون تابع صدا نزدم میتونی تابع رو برداری یا صداش بزنی

**Comment by Matinpirvali** [comment]
کدوم تابع رو

**Comment by Dadmehr0** [comment]
> کدوم تابع رو باید صدا کنم یا اگه لطف کنید داخل پکیج بذارید ممنون می شم

تابع خارو رداشتم نسخه win داخل فولدر GUI اجرا کنید

**Comment by Dadmehr0** [comment]
این مشکل حل شده و تست اگر مشکلی بود issuse کنید ممنون

**Comment by Dadmehr0** [comment]
این مشکل حل شده و تست اگر مشکلی بود issuse کنید ممنون
