### ISSUE TITLE
مشکل فونت ها در لینوکس 

### ISSUE THREAD

**Issue by BDadmehr0** [Matinpirvali/tmr_p#5]
برنامه در لینوکس از فونت عربی و فارسی ساپورت نمیکنه و برعکس دیده میشه. ولی در ویندوز مشکلی نداره 
کدی بنویسید که فونت های فارسی را ساپورت کند

**Comment by Matinpirvali** [comment]
برای استفاده از فونت فارسی در برنامه‌های تحت وب مبتنی بر Tkinter در لینوکس، می‌توانید مراحل زیر را دنبال کنید:

1. نصب فونت فارسی: ابتدا باید فونت فارسی مورد نظر خود را در سیستم عامل لینوکس نصب کنید. برای این کار، فونت فارسی را از یک منبع معتبر دانلود کرده و سپس آن را در مسیری که فونت‌ها در لینوکس قرار دارند (معمولاً `/usr/share/fonts` یا `~/.fonts`) کپی کنید.

2. تنظیمات Tkinter: برای استفاده از فونت فارسی، باید تنظیماتی در Tkinter اعمال کنید. می‌توانید از متد `option_add` برای تنظیم فونت استفاده کنید. قطعه کد زیر را در برنامه‌ی خود قرار دهید:

```python
import tkinter as tk

# تنظیم فونت فارسی
root = tk.Tk()
font_name = "نام_فونت_فارسی"
font_size = 12
root.option_add("*Font", (font_name, font_size))

# کد بقیه برنامه‌ی شما...
root.mainloop()
```

در این کد، `نام_فونت_فارسی` را با نام فونت فارسی مورد نظرتان جایگزین کنید.

3. تست برنامه: برنامه‌ی خود را اجرا کنید و مطمئن شوید که فونت فارسی به درستی بر روی Tkinter اعمال شده است.

با انجام این مراحل، باید بتوانید از فونت فارسی در Tkinter استفاده کنید. توجه داشته باشید که نام فونت فارسی باید با نامی که در سیستم عامل لینوکس نصب کرده‌اید، یکسان باشد. همچنین، اگر فونت مورد نظرتان در مسیر مشخصی قرار دارد، باید آن را در مسیر مناسب کپی کنید یا مسیر را در کد متغیر `font_name` تنظیم کنید.

**Comment by Matinpirvali** [comment]
به عنوان مثال، فونت "B Nazanin" را می‌توانید نصب کنید. این فونت یکی از فونت‌های فارسی محبوب است. برای نصب این فونت در لینوکس، مراحل زیر را دنبال کنید:

1. دریافت فونت: فونت "B Nazanin" را از منبع معتبری دانلود کنید. می‌توانید آن را از سایت‌های مختلفی مانند FontRiver، PersianFonts یا غیره پیدا کنید. بهتر است از سایت‌های معتبر و امن برای دریافت فونت استفاده کنید.

2. استقرار فونت: پس از دانلود فونت "B Nazanin"، فایل فونت را از حالت فشرده خارج کنید. سپس فایل فونت با پسوند `.ttf` را در مسیر `/usr/share/fonts` کپی کنید. اگر این مسیر وجود ندارد، می‌توانید آن را ایجاد کنید.

   به عنوان مثال، فرض کنید فونت "B Nazanin" را در پوشه‌ی Downloads قرار دارید. می‌توانید از دستور زیر برای کپی فایل فونت استفاده کنید:

   ```bash
   sudo cp ~/Downloads/B_Nazanin.ttf /usr/share/fonts/
   ```

   توجه داشته باشید که برای اجرای این دستور نیاز به دسترسی ادمین (sudo) دارید.

3. به‌روزرسانی کش فونت: بعد از کپی فونت، برای به‌روزرسانی کش فونت‌ها در لینوکس، دستور زیر را اجرا کنید:

   ```bash
   sudo fc-cache -f -v
   ```

   این دستور باعث به‌روزرسانی فهرست فونت‌های سیستم خواهد شد.

حالا شما می‌توانید از فونت "B Nazanin" در برنامه‌های Tkinter خود استفاده کنید، مطابق مراحلی که قبلاً در پاسخ قبلی توضیح داده شده است.

**Comment by BDadmehr0** [comment]
راهی پیدا نکردم این ایده هم نشد

**Comment by BDadmehr0** [comment]
برای لینوکس بهتره از کتابخانه گرافیکی دیگه ای استفاده بشه حداقل نه از tk
